[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "An EPUB renderer for mdbook."
name = "mdbook-epub"
version = "0.4.31"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Michael-F-Bryan/mdbook-epub"
documentation = "https://docs.rs/mdbook-epub"
keywords = ["epub", "mdbook", "documentation"]
categories = ["command-line-interface", "development-tools"]
edition = "2021"

[package.metadata.release]
sign-commit = true

[badges]
travis-ci = { repository = "Michael-F-Bryan/mdbook-epub", branch = "master" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "mdbook-epub"
doc = false

[dependencies]
epub-builder = "0.5"
#epub-builder = { path = "../epub-builder-blandger" }
#epub-builder = { git = "https://github.com/blandger/epub-builder.git", branch = "navigation_opt_fix" }
thiserror = "1.0"
anyhow = "1.0.40"
pulldown-cmark = "0.9.3"
semver = "0.11"
serde = "1.0.17"
serde_derive = "1.0"
serde_json = "1.0.96"
structopt = "0.3.26"
mime_guess = "2.0"
env_logger = "0.10.0"
log = "0.4.17"
#mdbook = { version = "0.4.31", default-features = false }
#mdbook = { path = "../mdBook-blandger" }
mdbook = { git = "https://github.com/blandger/mdBook.git", branch = "feature/links_preprocessor" }
handlebars = "4.3.7"
toml = "0.5.11"
html_parser = "0.6.2"
url = "2.3"
ureq = "2.5"
const_format = "0.2.30"

[dev-dependencies]
tempdir = "0.3.7"
epub = "2.1.1"
serial_test = "0.5"
mockall = "0.11"
env_logger = "*"
